public enum RequestType {
    LOGIN, LOGOUT, SIGNUP, GET_AVAILABLE_BOOKS, GET_BORROWED_BOOKS, ADD_BORROW, LOGIN_LIBRARIAN, SEARCH_LIBRARY_USER,
    RETURN_BOOK, ADD_BOOK, GET_ALL_BOOKS, SEARCH_BOOK, FILTER_BOOKS, RECOMMEND_BOOK
}
